function plotSPDLibraryToChromDiagramAndSPDPlot(app)
%PLOTSPDLIBRARYTOCHROMDIAGRAMANDSPDPLOT Summary of this function goes here
%% Plot all xy to chrom diagram
scatter(app.UIAxes_ChromDiagram,...
    app.xyuserSPDLibrary(:,1),...
    app.xyuserSPDLibrary(:,2),...
    tag = "xySPDs",...
    sizeData = 100, ...
    color = 'k'); %plot them
hold(app.UIAxes_ChromDiagram,'on');
scatter(app.UIAxes_ChromDiagram,[],[],tag="filledxySPDs");
%Put numbers inside of them
strValues(:,1) = strtrim(cellstr(num2str([1:size(app.xyuserSPDLibrary,1)]' )) );
text(app.UIAxes_ChromDiagram,...
    app.xyuserSPDLibrary(:,1),app.xyuserSPDLibrary(:,2),strValues,...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'fontsize', 12);
%% Plot spd library to spd figure
plot(app.UIAxes_ImportedSPDs,...
    380:app.wlIntUserImported_Prop:780,...
    app.userSPDLibrary(:,1:end),...
    LineStyle="--");

end

