function plotSPDLibraryToChromDiagramAndSPDPlot(app)
%PLOTSPDLIBRARYTOCHROMDIAGRAMANDSPDPLOT Summary of this function goes here
% hold(app.UIAxes_ChromDiagram,'off'); %clear old
hold(app.UIAxes_ChromDiagram,'on'); %hold on 
plotChromDiagram(2,app.UIAxes_ChromDiagram); %add a 2 deg chrom diagram to the axis handle

pbaspect(app.UIAxes_ChromDiagram,[1 1 1]);
%% Plot all xy to chrom diagram
scatter(app.UIAxes_ChromDiagram,...
    app.xyuserSPDLibrary(:,1),...
    app.xyuserSPDLibrary(:,2),...
    tag = "xySPDs",...
    sizeData = 100, ...
    color = 'k'); %plot them
hold(app.UIAxes_ChromDiagram,'on');
currentFilledxy=scatter(app.UIAxes_ChromDiagram,app.xyuserSPDLibrary(:,1),app.xyuserSPDLibrary(:,2),tag="filledxySPDs");
currentFilledxy.MarkerFaceColor = [0 0.8 0]; %green
%             currentFilledxy.
currentFilledxy.MarkerFaceAlpha = 0.25;
currentFilledxy.SizeData = 100;
%Put numbers inside of them
strValues(:,1) = strtrim(cellstr(num2str([1:size(app.xyuserSPDLibrary,1)]' )) );
text(app.UIAxes_ChromDiagram,...
    app.xyuserSPDLibrary(:,1),app.xyuserSPDLibrary(:,2),strValues,...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'fontsize', 12);
%% Plot spd library to spd figure
plot(app.UIAxes_ImportedSPDs,...
    app.wlVecProgram,...
    app.userSPDLibrary(:,1:end),...
    LineStyle="--");

end

